export const START_AUTH='START_AUTH';
export const START_REQUEST='START_REQUEST';
export const GUEST_USER='GUEST_USER';
export const RESP_ERROR='RESP_ERROR';

export const USER_LOGIN='USER_LOGIN';
export const FORGOT_PASSWORD='FORGOT_PASSWORD';
