export const START_ACTIONS='START_ACTIONS';
export const GET_PREVIOUSE_PAPERSET='GET_PREVIOUSE_PAPERSET';
export const GET_PREVIOUSE_PAPERS='GET_PREVIOUSE_PAPERS';
export const GET_YEARS='GET_YEARS';
export const GET_PDF_DATA='GET_PDF_DATA';
export const GET_QUESTION_SET='GET_QUESTION_SET';
export const GET_PRACTICE_EXAM='GET_PRACTICE_EXAM';
