const images={
  iconFacebook:require('../assets/images/facebook.png'),
  iconGoogle:require('../assets/images/google.png'),
  iconRegister:require('../assets/images/register.png'),
  iconNotification:require('../assets/images/ic_notif_active.png'),
      profileImage:require('../assets/images/aa.jpg'),
      homeActive:require('../assets/images/homeactive.gif'),
      homeInactive:require('../assets/images/home.gif'),
  icoDiscussActive:require('../assets/images/discussionActive.gif'),
   icoDiscussInactive:require('../assets/images/discussion.gif'),
   iconNotifyActive:require('../assets/images/testActive.gif'),
   iconNotifyInActive:require('../assets/images/test.gif'),
   iconOther_active:require('../assets/images/admitcardActive.gif'),
   iconOther_Inactive:require('../assets/images/admitcard.gif'),
    introJob:require('../assets/images/introScreenJobs.png'),
    introAdmitCard:require('../assets/images/introScreenAdmit.png'),
    introTest:require('../assets/images/introScreentest.png'),
    introDiscuss:require('../assets/images/introScreenGroup.png'),
    bookmarmActive:require('../assets/images/bookmarkActive.gif'),
    bookmarmInactive:require('../assets/images/bookmark.gif'),
    likesActive:require('../assets/images/likeactive.gif'),
    likesInActive:require('../assets/images/like.gif'),
    linkActive:require('../assets/images/link.gif'),
    iconBack:require('../assets/images/arrow_back.png'),
    iconPreviosePaper:require('../assets/images/pewviouspaper.gif'),
    iconClose:require('../assets/images/close.png'),
    iconGallary:require('../assets/images/gallery.png'),
    iconCamera:require('../assets/images/camera.png'),
    iconPdf:require('../assets/images/pdf.gif'),

    iconTestBack:require('../assets/images/arrow-left.gif'),
    iconTestNext:require('../assets/images/arrow-right.gif'),
    iconTime:require('../assets/images/timer.gif')
};
export default images;
