export const START_ACTIONS='START_ACTIONS';
export const END_ACTIONS='END_ACTIONS';
export const POST_QUESTION='POST_QUESTION';
export const GET_POSTED_QUESTION='GET_POSTED_QUESTION';
export const GET_COMMENT_DATA='GET_COMMENT_DATA'
export const POST_COMMENT_DATA='POST_COMMENT_DATA';
export const POST_REWARD_REPORT='POST_REWARD_REPORT';
