export const START_REQUEST='START_REQUEST';
export const END_REQUEST='END_REQUEST';
export const REQUEST_ERROR='REQUEST_ERROR';

export const ADVERTISE_DATA='ADVERTISE_DATA';
export const ADVERTISE_SUB_DATA='ADVERTISE_SUB_DATA';

export const GET_SINGLE_JOB='GET_SINGLE_JOB';

export const SEARCH_JOBS='SEARCH_JOBS';
